// The pipeline, declared.   Rendered by scripts/pipeline-map.js
//
// Nothing here is inferred from an AST, because the facts worth drawing are not
// in the syntax: which branch means what, what costs a credit, where a row is
// dropped on purpose. Those are read out of the code by a human once and then
// held in place by three machine checks -- see the header of pipeline-map.js.
//
// Rules for editing this file:
//   * Anchor a declaration, never a line number and never comment text.
//   * Write {MIN_FIT}, never 50. Values come from source.
//   * A node's `note` is the point. The diagram shows shape; the note says why.
//   * If a check fails because you renamed something, fix the anchor here in the
//     same commit. If it fails because you ADDED an action, table or section,
//     the map is genuinely missing something -- add a node or scope it out.
//
// The maintenance cost is real: ~60 anchors, and every new edge-function action
// or SQL object needs a decision. That cost is the price of the diagram being
// worth trusting. A generator that inferred everything would be free, and worth
// nothing.

module.exports = {
  constants: [
    { name: 'MAX_AGE_DAYS',        file: 'index.html' },
    { name: 'MIN_FIT',             file: 'index.html' },
    { name: 'SCORE_BATCH',         file: 'index.html' },
    { name: 'AUTO_MAX',            file: 'index.html' },
    { name: 'KEEP_TOP',            file: 'index.html' },
    { name: 'KEEP_UNTOUCHED_DAYS', file: 'index.html' },
    { name: 'FOLLOWUP_DAYS',       file: 'index.html' },
    { name: 'LIST_CAP',            file: 'index.html' },
    { name: 'WORK_FIT',            file: 'index.html' },
    { name: 'STRONG_FIT',          file: 'index.html' },
    { name: 'STRONG_REACH',        file: 'index.html' },
    { name: 'CLOSING_DAYS',        file: 'index.html' },
    { name: 'TOK_CAP',             file: 'index.html' },
    { name: 'COST', file: 'supabase/functions/api/index.ts', object: true },
    { name: 'LLM_TOK_CAP', file: 'supabase/functions/api/index.ts' },
    { name: 'DS_MODELS',  file: 'index.html',                        strings: true },
    { name: 'LLM_MODELS', file: 'supabase/functions/api/index.ts',   strings: true },
    { name: 'FLAG_P',     file: 'index.html' },
    { name: 'SPAN_FLOOR', file: 'index.html' },
    { name: 'JUDGE_BATCH',     file: 'index.html' },
    { name: 'MAX_JUDGE_BATCH', file: 'supabase/functions/api/index.ts' },
    { name: 'FLAG_CODES',       file: 'index.html',                          keys:  true },
    { name: 'JUDGE_FLAG_CODES', file: 'supabase/functions/_shared/judge.ts', array: true },
  ],

  /* ── invariants ──────────────────────────────────────────────────────────
     Two constants in two runtimes that have to hold the same value, where
     nothing in either file can tell. Unlike the rest of this spec these are not
     about the diagram at all -- they are here because this is the one program
     that already reads named constants out of every runtime, and a check with
     no home does not get written. */
  invariants: [
    { equal: ['TOK_CAP', 'LLM_TOK_CAP'],
      why: 'The browser sends max_tokens: TOK_CAP and the edge function clamps it to LLM_TOK_CAP.\n' +
           '        If the server number is the smaller one every hosted call is silently trimmed below\n' +
           '        what the app asked for, and the only symptom is truncated JSON that grabJSON throws on\n' +
           '        -- after the credit was spent. If the app number is the smaller one the extra ceiling\n' +
           '        on the server is dead. Move one, move both, in the same commit.' },

    { equal: ['DS_MODELS', 'LLM_MODELS'],
      why: 'The same tier name has to mean the same model on both paths. index.html picks the\n' +
           '        model itself when the user brought their own key; the edge function picks it from\n' +
           '        its own whitelist when we are paying. If the two maps drift, the same button scores\n' +
           '        on a different model depending on whose key paid, and nothing anywhere says so --\n' +
           '        the scores just stop being comparable between users.' },

    { equal: ['JUDGE_BATCH', 'MAX_JUDGE_BATCH'],
      why: 'The browser slices a search into batches of JUDGE_BATCH postings; the edge function\n' +
           '        rejects any batch longer than MAX_JUDGE_BATCH. If the app number is the larger one\n' +
           '        every full batch comes back 400 and a whole search goes unjudged -- and scoreAndCut\n' +
           '        catches that by design, so the symptom is not an error but flags quietly missing\n' +
           '        from every row. If the server number is the larger one its ceiling is dead.' },

    { equal: ['FLAG_CODES', 'JUDGE_FLAG_CODES'],
      why: 'The ten flag codes are written out twice: as keys in index.html, which decides what\n' +
           '        DeepSeek may return and how each one is spelled in the UI, and as an array in\n' +
           '        judge.ts, which decides what Jev is actually asked. Adding a code to one only is\n' +
           '        silent in both directions -- a flag the model can raise that is never judged, or a\n' +
           '        judgement whose answer nothing reads. Neither errors; both just quietly do less\n' +
           '        than they look like they do.' },
  ],

  diagrams: [
    { id: 'arrival', file: 'JT Intake', title: 'Intake — the seven doors',
      intro: 'Every way a job can enter, and the one that does not go through the front.',
      neighbours: ['JT Board Search', 'JT Scoring', 'JT Storage'] },
    { id: 'board', file: 'JT Board Search', title: 'Board search — the long path',
      intro: 'From the click to the first saved row: query building, the free triage, and what gets thrown away before anything is paid for.',
      neighbours: ['JT Edge Function', 'JT Scoring', 'JT Storage'] },
    { id: 'server', file: 'JT Edge Function', title: 'The edge function',
    intro: 'One POST, twelve actions, a service-role key. The server is a credential broker and a meter — there is no job table behind it.',
      neighbours: ['JT Credits', 'JT Scoring'] },
    { id: 'scoring', file: 'JT Scoring', title: 'Scoring',
      intro: 'The only step that costs money per job, and the only one whose output is a judgement rather than a fact.',
      neighbours: ['JT Credits', 'JT Storage'] },
    { id: 'storage', file: 'JT Storage', title: 'Storage and sync',
      intro: 'Where a job actually lives: one row per job, last writer wins within a row \u2014 and the blob it used to live in, still written, no longer read.',
      neighbours: ['JT Render'] },
    { id: 'credits', file: 'JT Credits', title: 'Credits and the ledger',
      intro: 'Three places money is spent, four places it comes back, and what the usage ledger records about each.',
      neighbours: ['JT Edge Function'] },
    { id: 'render', file: 'JT Render', title: 'Render — the colour law',
      intro: 'How a scored job becomes one row with at most one instruction on it.',
      neighbours: ['JT Intake'] },
  ],

  nodes: {
    /* ── intake ─────────────────────────────────────────────────────────── */
    'in.boards':  { diagram: 'arrival', group: 'the seven doors', kind: 'entry', label: 'runBoards — search the job boards',
      anchor: { file: 'index.html', fn: 'runBoards' }, section: "board search: every source's results, scored, 50+ kept",
      note: 'The only door that scores on the way in. Everything it keeps is already judged.' },
    'in.ats':     { diagram: 'arrival', group: 'the seven doors', kind: 'entry', label: 'runAts — pull a company feed',
      anchor: { file: 'index.html', fn: 'runAts' }, section: "board search: every source's results, scored, 50+ kept",
      note: 'No URL check, no age cut, no fit cut — an ATS feed is trusted.' },
    'in.suggest': { diagram: 'arrival', group: 'the seven doors', kind: 'entry', label: 'addSuggested — companies the model named',
      anchor: { file: 'index.html', fn: 'addSuggested' }, section: 'company discovery',
      note: 'Adds cold rows first, then optionally promotes any that are hiring.' },
    'in.csv':     { diagram: 'arrival', group: 'the seven doors', kind: 'entry', label: 'onCsv — import a spreadsheet',
      anchor: { file: 'index.html', fn: 'onCsv' }, section: 'shared bits',
      note: 'Scrubs the jobs-template.csv example rows before they can cost an LLM call.' },
    'in.paste':   { diagram: 'arrival', group: 'the seven doors', kind: 'entry', label: 'pasteJobDialog — add by hand',
      anchor: { file: 'index.html', fn: 'pasteJobDialog' }, section: 'shared bits',
      note: 'Trusted like a CSV row: no URL check, no age cut. A human typed it, so it is not guessed at.' },
    'in.cold':    { diagram: 'arrival', group: 'the seven doors', kind: 'entry', label: 'coldDialog — add a cold target',
      anchor: { file: 'index.html', fn: 'coldDialog' }, section: 'cold target',
      note: 'A company with no posting behind it. Enters as channel=cold, which is why a cold row has no posting date to age out.' },
    'in.backup':  { diagram: 'arrival', group: 'the seven doors', kind: 'entry', label: 'importBackup — restore a backup',
      anchor: { file: 'index.html', fn: 'importBackup' }, section: 'backup, restore, and sharing',
      note: 'The odd one out: swaps DB.profiles wholesale and never touches addJobs, keyOf or scoring. Restored jobs keep whatever scores they already had.' },

    'in.addJobs': { diagram: 'arrival', group: 'the funnel', kind: 'sync', label: 'addJobs — the one way in',
      anchor: { file: 'index.html', fn: 'addJobs' }, section: 'jobs', body: '74c00f',
      note: 'Six of the seven doors end here. Rejects empty titles and anything already seen.' },
    'in.keyOf':   { diagram: 'arrival', group: 'the funnel', kind: 'sync', label: 'keyOf — identity',
      anchor: { file: 'index.html', fn: 'keyOf' }, section: 'jobs', body: '176128',
      note: 'URL lowercased if there is one, else title|company|location. This is what "already seen" means.' },
    'in.auto':    { diagram: 'arrival', group: 'the funnel', kind: 'sync', label: 'autoScore — refuses above {AUTO_MAX}',
      anchor: { file: 'index.html', fn: 'autoScore' }, section: 'auto-scoring', body: 'a6f505',
      note: 'Every door except board search ends here. The {AUTO_MAX} cap is what stops a 400-row CSV silently starting a long paid run.' },

    /* ── board search ───────────────────────────────────────────────────── */
    'bd.portals':  { diagram: 'board', group: 'build the queries', kind: 'sync', label: 'portalsFor',
      anchor: { file: 'index.html', const: 'portalsFor' }, section: 'Apify: board search via Google' },
    'bd.queries':  { diagram: 'board', group: 'build the queries', kind: 'sync', label: 'buildBoardQueries',
      anchor: { file: 'index.html', fn: 'buildBoardQueries' }, section: 'Apify: board search via Google',
      note: 'Up to 14 Google site: queries. Binds location as "(place OR remote)" on portals only.' },
    'bd.live':     { diagram: 'board', group: 'build the queries', kind: 'sync', label: 'liveBoard — running tally',
      anchor: { file: 'index.html', fn: 'liveBoard' }, section: "board search: every source's results, scored, 50+ kept",
      note: 'Holds the per-origin ledger that becomes the usage report: found, unique_new, kept, exclusive.' },
    'bd.branch':   { diagram: 'board', group: 'build the queries', kind: 'branch', label: 'own Apify token?',
      anchor: { file: 'index.html', re: 'if\\(!ownApify\\(\\) && cloudNow\\(\\)\\)\\{' },
      note: 'Hosted: every source at once, one charge. Own token: a single Google run, no charge.' },
    'bd.hosted':   { diagram: 'board', group: 'build the queries', kind: 'net', label: "hosted('board_search')",
      anchor: { file: 'index.html', fn: 'hosted' }, section: 'Credits',
      note: 'Unwraps the edge-function error body. NEEDCREDITS is the one case that opens a dialog rather than throwing a message.' },

    'bd.filter':   { diagram: 'board', group: 'free triage — before anything is paid for', kind: 'sync', label: 'boardFilter',
      anchor: { file: 'index.html', fn: 'boardFilter' }, section: "board search: every source's results, scored, 50+ kept", body: 'cc19dc',
      note: 'Three counters, nothing else. There is deliberately no title-word filter — it threw away half of real searches, and every job is scored against the CV anyway.' },
    'bd.url':      { diagram: 'board', group: 'free triage — before anything is paid for', kind: 'branch', label: 'isPostingUrl',
      anchor: { file: 'index.html', fn: 'isPostingUrl' }, section: "board search: every source's results, scored, 50+ kept",
      note: 'A search results page is not a job. Per-host allow shapes, then a generic "looks searchy" reject.' },
    'bd.dropList': { diagram: 'board', group: 'free triage — before anything is paid for', kind: 'drop', label: 'dropped: a listing page',
      anchor: { file: 'index.html', re: 'dropped\\.listing\\+\\+' } },
    'bd.dropOld':  { diagram: 'board', group: 'free triage — before anything is paid for', kind: 'drop', label: 'dropped: older than {MAX_AGE_DAYS} days',
      anchor: { file: 'index.html', const: 'MAX_AGE_DAYS' }, section: "board search: every source's results, scored, 50+ kept",
      note: 'An unknown posting date is KEPT. Unknown is not old — only a date that is actually too old drops the row.' },
    'bd.dropDupe': { diagram: 'board', group: 'free triage — before anything is paid for', kind: 'drop', label: 'dropped: already seen',
      anchor: { file: 'index.html', re: 'dropped\\.dupe\\+\\+' },
      note: 'Two keys: keyOf, plus a looser title|company so the same job syndicated to three boards lands once.' },

    'bd.fromAts':  { diagram: 'board', group: 'ask the company directly', kind: 'net', label: 'fromAts — pull the real description',
      anchor: { file: 'index.html', fn: 'fromAts' }, section: "board search: every source's results, scored, 50+ kept",
      note: 'One feed pull per company, cached. Upgrades a Google snippet to the full posting, which is what moves confidence from low to high.' },
    'bd.atsOf':    { diagram: 'board', group: 'ask the company directly', kind: 'sync', label: 'atsOfUrl',
      anchor: { file: 'index.html', fn: 'atsOfUrl' }, section: "board search: every source's results, scored, 50+ kept" },
    'bd.atsPull':  { diagram: 'board', group: 'ask the company directly', kind: 'net', label: 'atsPull — public ATS JSON',
      anchor: { file: 'index.html', fn: 'atsPull' }, section: 'Credits' },
    'bd.closed':   { diagram: 'board', group: 'ask the company directly', kind: 'drop', label: 'dropped: the posting is gone',
      anchor: { file: 'index.html', re: 'if\\(!row\\)\\{ closed\\+\\+' },
      note: 'Feed loaded but this id is not in it, so the role was filled. A feed that FAILS to load proves nothing and the row is kept.' },

    /* ── edge function ──────────────────────────────────────────────────── */
    'sv.auth':    { diagram: 'server', group: 'every request', kind: 'branch', label: 'auth gate — 401 if no user',
      anchor: { file: 'supabase/functions/api/index.ts', re: 'await admin\\.auth\\.getUser\\(token\\)' },
      note: 'The function holds the service-role key and bypasses RLS entirely, so this user object is the ONLY thing scoping any query.' },
    'sv.switch':  { diagram: 'server', group: 'every request', kind: 'branch', label: 'switch (action)',
      anchor: { file: 'supabase/functions/api/index.ts', re: 'switch \\(b\\.action\\)' },
      note: 'One POST route, no path routing. An unmatched action is a 400.' },
    'sv.packs':   { diagram: 'server', group: 'actions', kind: 'sync', label: 'packs',
      anchor: { file: 'supabase/functions/api/index.ts', case: 'packs' }, note: 'Credit pack prices. Free, but still behind the auth gate.' },
    'sv.board':   { diagram: 'server', group: 'actions', kind: 'credit', label: 'board_search — {COST.boardSearch} credits',
      anchor: { file: 'supabase/functions/api/index.ts', case: 'board_search' },
      note: 'Fans out to six API sources and up to six Apify actors in parallel. One charge for the lot.' },
    'sv.report':  { diagram: 'server', group: 'actions', kind: 'sync', label: 'search_report',
      anchor: { file: 'supabase/functions/api/index.ts', case: 'search_report' },
      note: 'Client-reported yield per source. Validated: must be the caller\'s own search, under 15 minutes old, not already reported.' },
    'sv.llm':     { diagram: 'server', group: 'actions', kind: 'credit', label: 'llm — {COST.llm} credit',
      anchor: { file: 'supabase/functions/api/index.ts', case: 'llm' },
      note: 'The server sees an opaque prompt string. It does no scoring of its own and knows nothing about jobs.' },
    'sv.judge':   { diagram: 'server', group: 'actions', kind: 'credit', label: 'judge — {COST.llm} credit',
      anchor: { file: 'supabase/functions/api/index.ts', case: 'judge' },
      note: 'The scoring prompt\'s c and f fields, moved off DeepSeek onto a typed System One judgment: one choice (confidence), two scores (capability and targeting) and one noul per flag. One credit, refunded if Jev fails.' },
    'sv.judgeBatch': { diagram: 'server', group: 'actions', kind: 'credit', label: 'judge_batch — {COST.llm} credit',
      anchor: { file: 'supabase/functions/api/index.ts', case: 'judge_batch' },
      note: 'The same judgment for up to {MAX_JUDGE_BATCH} postings. Jev takes one state per request, so the server still makes one call per posting and only the round trip and the charge are batched -- which is what makes judging a whole search cost one credit instead of three hundred. A partial batch keeps the credit; a batch where every posting failed refunds.' },
    'sv.apStart': { diagram: 'server', group: 'actions', kind: 'credit', label: 'apify_start — {COST.apifyQuery} per query',
      anchor: { file: 'supabase/functions/api/index.ts', case: 'apify_start' } },
    'sv.mantiks': { diagram: 'server', group: 'actions', kind: 'credit', label: 'mantiks_contact — one contact, refunded on a miss',
      anchor: { file: 'supabase/functions/api/index.ts', case: 'mantiks_contact' },
      note: 'Two calls: find the posting in Mantiks (free), then ask who owns the req (1 lead credit). Tried before the Google roster; a miss refunds the user and falls through, so the question is never billed twice.' },
    'sv.apStat':  { diagram: 'server', group: 'actions', kind: 'net', label: 'apify_status',
      anchor: { file: 'supabase/functions/api/index.ts', case: 'apify_status' } },
    'sv.apItems': { diagram: 'server', group: 'actions', kind: 'net', label: 'apify_items',
      anchor: { file: 'supabase/functions/api/index.ts', case: 'apify_items' },
      note: 'Free to call, but this is where the real scrape cost is finally known and logged.' },
    'sv.apAbort': { diagram: 'server', group: 'actions', kind: 'net', label: 'apify_abort',
      anchor: { file: 'supabase/functions/api/index.ts', case: 'apify_abort' },
      note: 'Walking away from a run without aborting it is the one way to spend money for nothing.' },
    'sv.order':   { diagram: 'server', group: 'actions', kind: 'net', label: 'order — Razorpay',
      anchor: { file: 'supabase/functions/api/index.ts', case: 'order' } },
    'sv.verify':  { diagram: 'server', group: 'actions', kind: 'db', label: 'verify — HMAC, then grant',
      anchor: { file: 'supabase/functions/api/index.ts', case: 'verify' } },
    'sv.runs':    { diagram: 'server', group: 'actions', kind: 'db', label: 'apify_runs — who owns this run',
      anchor: { file: 'billing.sql', sql: 'public.apify_runs' },
      note: 'RLS on with zero policies: server-only by construction. Every apify_status and apify_items call checks ownership here first.' },

    /* ── scoring ────────────────────────────────────────────────────────── */
    'sc.cut':     { diagram: 'scoring', group: 'browser', kind: 'sync', label: 'scoreAndCut — batches of {SCORE_BATCH}',
      anchor: { file: 'index.html', fn: 'scoreAndCut' }, section: "board search: every source's results, scored, 50+ kept", body: 'e89c2a',
      note: 'Batches of {SCORE_BATCH} rather than the {AUTO_MAX}-guarded 6 used for rescoring, because a search can return hundreds. Those same hundreds are why this path alone scores on {DS_MODELS.flash}: rescoring from the Score button stays on {DS_MODELS.pro}, so one list can hold scores from both tiers and the {MIN_FIT} intake cut here is applied to flash scores. Everything it scored is then judged in one pass through judgeMany, after the loop rather than inside it; a judgement that fails costs the flags and never the scoring already paid for.' },
    'sc.batch':   { diagram: 'scoring', group: 'browser', kind: 'sync', label: 'scoreBatch',
      anchor: { file: 'index.html', fn: 'scoreBatch' }, section: 'scoring run',
      note: 'Descriptions cut to 700 chars. A row that already has a trustworthy date sends it, so the model is never asked to guess one.' },
    'sc.prompt':  { diagram: 'scoring', group: 'browser', kind: 'sync', label: 'sysPrompt — byte-identical prefix',
      anchor: { file: 'index.html', fn: 'sysPrompt' }, section: 'scoring prompt, built from THIS person',
      note: 'Nothing variable may go before "JOBS TO SCORE", or DeepSeek stops serving the prefix from prompt cache and every call costs full price.' },
    'sc.claude':  { diagram: 'scoring', group: 'browser', kind: 'branch', label: 'claude — own key, or ours?',
      anchor: { file: 'index.html', fn: 'claude' }, section: 'LLM',
      note: 'No local key plus cloud available means the hosted route and a credit. A local key goes direct to DeepSeek or Anthropic and costs nothing here.' },
    'sc.deepseek': { diagram: 'scoring', group: 'server', kind: 'net', label: 'DeepSeek — {LLM_MODELS.flash} here, {LLM_MODELS.pro} elsewhere',
      anchor: { file: 'supabase/functions/api/index.ts', re: 'const model = LLM_MODELS\\[' },
      note: 'The browser sends a tier name, never a model id -- our key pays, so the model is chosen server-side from a whitelist and an unknown tier falls back to pro. Board search is the one caller that asks for flash; every other feature is one call per click and stays on pro. Anthropic exists in this app but is client-side only, on the user\'s own key.' },
    'sc.refund':  { diagram: 'scoring', group: 'server', kind: 'credit', label: 'refund on empty or malformed',
      anchor: { file: 'supabase/functions/api/index.ts', fn: 'refund' },
      note: 'Charged first, so every failure path after the charge has to give it back. This was a real bug once: charged, then collapsed into "Server error".' },
    'sc.grab':    { diagram: 'scoring', group: 'back in the browser', kind: 'sync', label: 'grabJSON',
      anchor: { file: 'index.html', fn: 'grabJSON' }, section: 'LLM',
      note: 'Strips code fences and slices first { to last }. Throws on malformed output, which is caught one level up.' },
    'sc.keep':    { diagram: 'scoring', group: 'back in the browser', kind: 'sync', label: 'kept: fit {MIN_FIT}+',
      anchor: { file: 'index.html', const: 'MIN_FIT' }, section: "board search: every source's results, scored, 50+ kept" },
    'sc.below':   { diagram: 'scoring', group: 'back in the browser', kind: 'drop', label: 'dropped: scored under {MIN_FIT}',
      anchor: { file: 'index.html', re: 'else below\\+\\+' },
      note: 'The one place a paid-for row is thrown away. It was judged and it lost.' },
    'sc.rescore': { diagram: 'scoring', group: 'browser', kind: 'sync', label: 'runScoring \u2014 the Score button, batches of 6',
      anchor: { file: 'index.html', fn: 'runScoring' }, section: 'scoring run',
      note: 'The other scoring path, and the small one: a rescore of what is already in the list, guarded by {AUTO_MAX}. Because it is small it can afford a judgement per job; board search cannot.' },
    'sc.judge':   { diagram: 'scoring', group: 'back in the browser', kind: 'credit', label: 'judgeInto \u2014 {COST.llm} credit per JOB',
      anchor: { file: 'index.html', fn: 'judgeInto' }, section: 'scoring run',
      note: 'Per job, where a whole DeepSeek batch of {SCORE_BATCH} is also {COST.llm} credit \u2014 so judging one job this way is about twelve times the price of scoring one. The rescore path can carry that because {AUTO_MAX} caps it; the search path pays once per batch through judgeMany instead. Returns null rather than throwing: with no account, no credits or an own key the TypeSafe key is not reachable from the browser at all, and DeepSeek\'s own flags stand.' },
    'sc.judgeMany': { diagram: 'scoring', group: 'back in the browser', kind: 'credit', label: 'judgeMany \u2014 {COST.llm} credit per {JUDGE_BATCH}',
      anchor: { file: 'index.html', fn: 'judgeMany' }, section: 'Credits',
      note: 'What makes judging a whole search affordable: one charge and one round trip for {JUDGE_BATCH} postings, against one per job on the rescore path. The server still makes one Jev call per posting \u2014 Jev takes one state per request, and postings sharing a state would distract each other \u2014 so what is batched here is the trip and the meter, never the judgement itself. Runs once after the whole scoring loop rather than per batch of {SCORE_BATCH}, which is the difference between a handful of charges for a search and dozens.' },
    'sc.merge':   { diagram: 'scoring', group: 'back in the browser', kind: 'sync', label: 'mergeJudgment \u2014 Jev fires, DeepSeek explains',
      anchor: { file: 'index.html', fn: 'mergeJudgment' }, section: 'scoring run',
      note: 'Jev decides which flags are true above {FLAG_P}; the fact behind each comes from DeepSeek. A flag Jev raises that DeepSeek never mentioned shows with no fact rather than borrowing one from its neighbour.' },
    'sc.span':    { diagram: 'scoring', group: 'back in the browser', kind: 'sync', label: 'bestSentence \u2014 the quote, found not asked for',
      anchor: { file: 'index.html', fn: 'bestSentence' }, section: 'scoring run',
      note: 'The evidence span is located in the browser by matching the fact against the posting, so it costs nothing, works with no account, and is a substring of the posting by construction rather than by the model\'s good behaviour. Below {SPAN_FLOOR} it returns nothing: an unquoted flag is honest, a confidently wrong quote is not.' },
    'sc.unscored': { diagram: 'scoring', group: 'back in the browser', kind: 'sync', label: 'kept unscored',
      anchor: { file: 'index.html', re: 'unscored\\.push\\(\\.\\.\\.part\\)' },
      note: 'The batch failed, but those rows were already paid for, so they are kept unjudged rather than lost. "Score new jobs" picks them up later.' },

    /* ── storage ────────────────────────────────────────────────────────── */
    'st.save':    { diagram: 'storage', group: 'browser', kind: 'sync', label: 'save',
      anchor: { file: 'index.html', fn: 'save' }, section: 'rows: profiles and jobs',
      note: 'Writes the blob every time, and the rows as well once this account has migrated. The blob is no longer read at that point \u2014 it is the offline copy and the rollback, and a rollback copy is only worth keeping if it is current.' },
    'st.saveRows': { diagram: 'storage', group: 'browser', kind: 'sync', label: 'saveRows \u2014 only what changed',
      anchor: { file: 'index.html', fn: 'saveRows' }, section: 'rows: profiles and jobs',
      note: 'Diffs this browser\'s rows against what the server was last known to hold and sends the difference. Profiles go first, because a job row references profiles.id and the insert policy checks it. A job that left the list is marked deleted, not removed: an offline tab still holds it and would otherwise add it back.' },
    'st.coerce':  { diagram: 'storage', group: 'browser', kind: 'sync', label: 'jobRow / coerceJob \u2014 27 strings <-> a typed row',
      anchor: { file: 'index.html', fn: 'jobRow' }, section: 'rows: profiles and jobs',
      note: 'Every field of every job is a string in this app; a row is typed. Anything a column cannot hold unchanged \u2014 a CSV date of "12/03/2025", a fit of 72.5 \u2014 is kept verbatim in extras and laid back over the row on read, because dropping it would be a silent permanent edit to somebody\'s data. scripts/selfcheck-rows.js asserts the round trip.' },
    'st.migrate': { diagram: 'storage', group: 'browser', kind: 'branch', label: 'migrateRows \u2014 blob to rows, once',
      anchor: { file: 'index.html', fn: 'migrateRows' }, section: 'rows: profiles and jobs',
      note: 'Counts the rows back before setting triage:migrated. A migration that reports success and did not run is how you lose everything in one step \u2014 on a mismatch it stays on the blob and says so.' },
    'st.put':     { diagram: 'storage', group: 'browser', kind: 'branch', label: 'put — local only, or sync too?',
      anchor: { file: 'index.html', fn: 'put' }, section: 'accounts and cloud sync', body: 'a1daa8',
      note: 'The local write always happens first, so a failed sync never loses work.' },
    'st.localOnly': { diagram: 'storage', group: 'browser', kind: 'sync', label: 'LOCAL_ONLY — keys never leave the device',
      anchor: { file: 'index.html', const: 'LOCAL_ONLY' }, section: 'accounts and cloud sync',
      note: 'The user\'s own DeepSeek and Apify keys match this and are deliberately never synced.' },
    'st.putLocal': { diagram: 'storage', group: 'browser', kind: 'db', label: 'putLocal — localStorage',
      anchor: { file: 'index.html', fn: 'putLocal' }, section: 'accounts and cloud sync' },
    'st.down':    { diagram: 'storage', group: 'browser', kind: 'branch', label: 'CLOUD_DOWN latch',
      anchor: { file: 'index.html', const: 'cloudDown' }, section: 'accounts and cloud sync',
      note: 'Latches on the first timeout so one dead call does not become four serial 8-second hangs.' },
    'st.blob':    { diagram: 'storage', group: 'Supabase', kind: 'db', label: 'user_state \u2014 the blob, and the small keys',
      anchor: { file: 'schema.sql', sql: 'public.user_state' },
      note: 'Was the only store: every job inside one text column, so a new job rewrote the whole list and two tabs searching at once lost one tab\'s work. Still written on every save as the offline copy and the rollback, and still the home of the keys that are not rows \u2014 triage:current, triage:auto, triage:migrated \u2014 but once an account has migrated, nothing reads the job blob.' },
    'st.profiles': { diagram: 'storage', group: 'Supabase', kind: 'db', label: 'profiles \u2014 one row per profile',
      anchor: { file: 'schema.sql', sql: 'public.profiles' },
      note: 'Keyed by the app\'s own p_... id as well as a uuid, because DB.profiles is keyed by that string and a uuid the app never sees could not rebuild it. Carries the role and discoverable stubs the employer side will need.' },
    'st.jobs':    { diagram: 'storage', group: 'Supabase', kind: 'db', label: 'jobs \u2014 one row per job',
      anchor: { file: 'schema.sql', sql: 'public.jobs' },
      note: 'Unique on (profile_id, job_key), where job_key is keyOf \u2014 the identity the app already used to mean "have I seen this posting". Two tabs editing two different jobs now write two different rows. Two tabs editing the same job still lose one: last writer wins, deliberately, because the alternative is a conflict screen in an app with nowhere to put one.' },
    'st.index':   { diagram: 'storage', group: 'Supabase', kind: 'db', label: 'job_index \u2014 the shared corpus',
      anchor: { file: 'schema.sql', sql: 'public.job_index' },
      note: 'Shared for the same reason as job_checks: acquiring a posting costs ~16x what deciding about it costs, so the row bought once and served to everyone is the only one that scales. public.jobs is what a person has chosen to track; this is everything known. Two tiers -- a full row carries a real description and can be judged, a thin row comes from a board sitemap and carries none, so it is a shortlist candidate and never an answer. dedup_key is generated rather than written, because the same role posted to five boards has five urls and a key each caller computes is a key that disagrees with itself.' },
    'st.checks':  { diagram: 'storage', group: 'Supabase', kind: 'db', label: 'job_checks \u2014 is the posting still listed',
      anchor: { file: 'schema.sql', sql: 'public.job_checks' },
      note: 'The one table here that is not per-user, and that is the point: whether a posting is still listed is a fact about the posting, so checking it once serves everyone who holds it. Written by scripts/index/verify.js through the service role; readable by any signed-in user and writable by none, since there is no user_id to scope by and a job_key is only a url. Liveness is a set difference over the boards\u2019 own daily indexes, never a fetch \u2014 every job url sampled returned 403, and naukri.com/robots.txt disallows AI crawlers outright.' },
    'st.names':   { diagram: 'storage', group: 'Supabase', kind: 'db', label: 'usernames',
      anchor: { file: 'schema.sql', sql: 'public.usernames' },
      note: 'Claimed by the only trigger in the schema, which fires on account creation and never on a job.' },

    /* ── credits ────────────────────────────────────────────────────────── */
    'cr.spendSearch': { diagram: 'credits', group: 'spend', kind: 'credit', label: 'spend_search',
      anchor: { file: 'billing.sql', sql: 'public.spend_search' },
      note: 'Free pot first, then paid balance, then null. Every pot check sits inside the UPDATE WHERE, so two parallel calls cannot both spend the last credit. When the free searches run out it also flips free_tier off — which is the moment free AI scoring ends.' },
    'cr.spendLlm':    { diagram: 'credits', group: 'spend', kind: 'credit', label: 'spend_llm',
      anchor: { file: 'billing.sql', sql: 'public.spend_llm' },
      note: 'The free branch decrements by the amount asked for, never below zero; a call larger than the remaining free balance falls through to paid credits.' },
    'cr.refundFree':  { diagram: 'credits', group: 'give back', kind: 'credit', label: 'refund_free',
      anchor: { file: 'billing.sql', sql: 'public.refund_free' } },
    'cr.add':         { diagram: 'credits', group: 'give back', kind: 'credit', label: 'add_credits',
      anchor: { file: 'billing.sql', sql: 'public.add_credits' } },
    'cr.paid':        { diagram: 'credits', group: 'give back', kind: 'db', label: 'mark_order_paid',
      anchor: { file: 'billing.sql', sql: 'public.mark_order_paid' },
      note: 'Idempotent by a status guard, so an order can never be credited twice however many times the webhook fires.' },
    'cr.credits':     { diagram: 'credits', group: 'tables', kind: 'db', label: 'credits',
      anchor: { file: 'billing.sql', sql: 'public.credits' },
      note: 'Select-own only, with no insert or update policy at all — a user cannot top themselves up.' },
    'cr.orders':      { diagram: 'credits', group: 'tables', kind: 'db', label: 'orders',
      anchor: { file: 'billing.sql', sql: 'public.orders' } },
    'cr.usage':       { diagram: 'credits', group: 'tables', kind: 'db', label: 'usage_events — the ledger',
      anchor: { file: 'billing.sql', sql: 'public.usage_events' },
      note: 'Five kinds: api, error, scrape, llm, yield. The error rows exist because a source that threw every time was otherwise indistinguishable from one that was never called.' },
    'cr.log':         { diagram: 'credits', group: 'tables', kind: 'db', label: 'logUsage — never throws',
      anchor: { file: 'supabase/functions/api/index.ts', fn: 'logUsage' },
      note: 'Accounting must not be able to fail a request that already succeeded.' },

    /* ── render ─────────────────────────────────────────────────────────── */
    'rd.render':   { diagram: 'render', group: 'draw', kind: 'sync', label: 'renderUnapplied',
      anchor: { file: 'index.html', fn: 'renderUnapplied' }, section: 'Unapplied' },
    'rd.closing':  { diagram: 'render', group: 'the cascade — at most one instruction per row', kind: 'branch', label: 'Closing soon — posted {CLOSING_DAYS}+ days ago',
      anchor: { file: 'index.html', fn: 'isClosing' }, section: 'the colour law, in code',
      note: 'Checked first: the nearer deadline beats the better opportunity.' },
    'rd.strong':   { diagram: 'render', group: 'the cascade — at most one instruction per row', kind: 'branch', label: 'Do these first — fit {STRONG_FIT}+, reach {STRONG_REACH}+',
      anchor: { file: 'index.html', const: 'STRONG_FIT' }, section: 'the colour law, in code' },
    'rd.worth':    { diagram: 'render', group: 'the cascade — at most one instruction per row', kind: 'branch', label: 'Worth a shot — over fit {WORK_FIT}',
      anchor: { file: 'index.html', const: 'WORK_FIT' }, section: 'the colour law, in code' },
    'rd.below':    { diagram: 'render', group: 'the cascade — at most one instruction per row', kind: 'sync', label: 'Below the bar — folded, not deleted',
      anchor: { file: 'index.html', const: 'foldSect' }, section: 'the daily view',
      note: 'Kept, because a score is a judgement rather than a fact.' },
    'rd.sort':     { diagram: 'render', group: 'order', kind: 'sync', label: 'sortList',
      anchor: { file: 'index.html', const: 'sortList' }, section: 'MAIN APP' },
    'rd.rank':     { diagram: 'render', group: 'order', kind: 'sync', label: 'rankOf — fit^0.65 x reach^0.35 x confidence',
      anchor: { file: 'index.html', fn: 'rankOf' }, section: 'jobs',
      note: 'Fit and reachability are two axes on purpose. A perfect-fit role at a famous employer scores high on one and low on the other.' },
    'rd.cap':      { diagram: 'render', group: 'order', kind: 'sync', label: 'LIST_CAP — {LIST_CAP} rows per fold',
      anchor: { file: 'index.html', const: 'LIST_CAP' }, section: 'theme' },
  },

  edges: [
    { from: 'in.boards', to: 'in.addJobs' }, { from: 'in.ats', to: 'in.addJobs' },
    { from: 'in.suggest', to: 'in.addJobs' }, { from: 'in.csv', to: 'in.addJobs' },
    { from: 'in.paste', to: 'in.addJobs' }, { from: 'in.cold', to: 'in.addJobs' },
    { from: 'in.addJobs', to: 'in.keyOf', label: 'already seen?' },
    { from: 'in.keyOf', to: 'in.auto', label: 'new rows' },

    { from: 'bd.portals', to: 'bd.queries' }, { from: 'bd.queries', to: 'bd.branch' },
    { from: 'bd.branch', to: 'bd.hosted', label: 'ours' },
    { from: 'bd.hosted', to: 'bd.live' }, { from: 'bd.live', to: 'bd.filter' },
    { from: 'bd.filter', to: 'bd.url' },
    { from: 'bd.url', to: 'bd.dropList', label: 'a search page', style: 'drop' },
    { from: 'bd.filter', to: 'bd.dropOld', label: 'age > {MAX_AGE_DAYS}', style: 'drop' },
    { from: 'bd.filter', to: 'bd.dropDupe', label: 'seen before', style: 'drop' },
    { from: 'bd.url', to: 'bd.fromAts', label: 'a real posting' },
    { from: 'bd.fromAts', to: 'bd.atsOf' }, { from: 'bd.atsOf', to: 'bd.atsPull' },
    { from: 'bd.atsPull', to: 'bd.closed', label: 'not in the feed', style: 'drop' },

    { from: 'sv.auth', to: 'sv.switch' },
    ...['packs', 'board', 'report', 'llm', 'judge', 'judgeBatch', 'apStart', 'apStat', 'apItems', 'apAbort', 'order', 'verify']
      .map(a => ({ from: 'sv.switch', to: `sv.${a}` })),
    { from: 'st.index', to: 'st.checks', label: 'still listed?' },
    { from: 'sv.mantiks', to: 'sv.apStart', label: 'miss → Google' },
    { from: 'sv.apStart', to: 'sv.runs' }, { from: 'sv.apStat', to: 'sv.runs', label: 'owns it?' },

    { from: 'sc.cut', to: 'sc.batch' }, { from: 'sc.batch', to: 'sc.prompt' },
    { from: 'sc.prompt', to: 'sc.claude' },
    { from: 'sc.claude', to: 'sc.deepseek', label: 'our key, {COST.llm} credit' },
    { from: 'sc.deepseek', to: 'sc.refund', label: 'empty or 502', style: 'drop' },
    { from: 'sc.deepseek', to: 'sc.grab' },
    { from: 'sc.grab', to: 'sc.keep', label: 'fit {MIN_FIT}+' },
    { from: 'sc.grab', to: 'sc.below', label: 'under {MIN_FIT}', style: 'drop' },
    { from: 'sc.batch', to: 'sc.unscored', label: 'batch threw', style: 'drop' },
    { from: 'sc.rescore', to: 'sc.batch' },
    { from: 'sc.rescore', to: 'sc.judge', label: 'one call per job' },
    { from: 'sc.cut', to: 'sc.judgeMany', label: 'once for the whole search' },
    { from: 'sc.judgeMany', to: 'sc.merge' },
    { from: 'sc.judge', to: 'sc.merge' }, { from: 'sc.grab', to: 'sc.merge' },
    { from: 'sc.merge', to: 'sc.span' },

    { from: 'st.save', to: 'st.put' }, { from: 'st.put', to: 'st.localOnly', label: 'a key?' },
    { from: 'st.put', to: 'st.putLocal', label: 'always, first' },
    { from: 'st.putLocal', to: 'st.blob', label: 'then sync' },
    { from: 'st.blob', to: 'st.down', label: 'timed out', style: 'drop' },
    { from: 'st.save', to: 'st.saveRows', label: 'migrated' },
    { from: 'st.saveRows', to: 'st.coerce' },
    { from: 'st.coerce', to: 'st.profiles', label: 'changed profiles' },
    { from: 'st.coerce', to: 'st.jobs', label: 'changed jobs' },
    { from: 'st.migrate', to: 'st.saveRows', label: 'once, then counts it back' },
    { from: 'st.blob', to: 'st.migrate', label: 'not migrated yet' },
    { from: 'st.saveRows', to: 'st.down', label: 'timed out', style: 'drop' },

    { from: 'cr.spendSearch', to: 'cr.credits' }, { from: 'cr.spendLlm', to: 'cr.credits' },
    { from: 'cr.spendSearch', to: 'cr.refundFree', label: 'nothing came back' },
    { from: 'cr.spendLlm', to: 'cr.refundFree', label: 'model failed' },
    { from: 'cr.refundFree', to: 'cr.credits' }, { from: 'cr.add', to: 'cr.credits' },
    { from: 'cr.orders', to: 'cr.paid', label: 'webhook' }, { from: 'cr.paid', to: 'cr.add' },
    { from: 'cr.log', to: 'cr.usage' },

    { from: 'rd.render', to: 'rd.closing' },
    { from: 'rd.closing', to: 'rd.strong', label: 'not closing' },
    { from: 'rd.strong', to: 'rd.worth', label: 'not strong' },
    { from: 'rd.worth', to: 'rd.below', label: 'under the bar' },
    { from: 'rd.closing', to: 'rd.sort' }, { from: 'rd.strong', to: 'rd.sort' },
    { from: 'rd.worth', to: 'rd.sort' },
    { from: 'rd.sort', to: 'rd.rank' }, { from: 'rd.sort', to: 'rd.cap' },
  ],

  /* Members of an enumerable set that are deliberately NOT on a map. Every one
     needs a reason: "we forgot" and "it does not belong" must not look alike. */
  outOfScope: {
    'schema.sql objects': {
      'public.delete_my_data': 'account deletion, not the job pipeline — and it is declared twice in schema.sql, so it could not be anchored unambiguously anyway',
      'public.handle_new_user': 'fires on account creation, never on a job',
      'public.username_available': 'sign-up, not ingestion',
      'public.login_email': 'sign-in, not ingestion',
      'public.claim_username': 'sign-up, not ingestion',
      'public.my_username': 'sign-in, not ingestion',
    },
    'index.html section banners': {
      'colour': 'CSS tokens — see CLAUDE.md, not this map',
      'the queue': 'CSS',
      'one job, opened': 'CSS',
      'theme': 'presentation, no data flow',
      'state': 'globals, drawn where they are used',
      'when was this posted': 'the posted_lo/posted_hi date quartet — a data model, worth its own map one day',
      'Apify': 'the run poller, drawn as the network edges that use it',
      'Apify: HR / recruiter contact finder (LinkedIn)': 'the contact finder is a separate feature from job ingestion',
      'LLM': 'the transport, drawn as claude in JT Scoring',
      'profile extraction': 'CV to profile, which happens once at onboarding and not per job',
      'assessing a direction the person names themselves': 'onboarding',
      'trimming the list': 'manual retention, not arrival',
      'retention': 'the untouched purge runs once per boot, not per job',
      'CSV': 'the parser, drawn as onCsv in JT Intake',
      'scoring run': 'the manual rescore path, drawn as scoreBatch in JT Scoring',
      'ONBOARDING': 'first-run flow, before any job exists',
      'MAIN APP': 'a layout banner, not a stage',
      'the daily view': 'a view over jobs that already arrived',
      'Applied — review': 'after the application, past the pipeline this map covers',
      'Dashboard': 'a view over jobs that already arrived',
      'plot drag': 'a UI gesture',
      'shared bits': 'dialog helpers',
      'sign in': 'auth, drawn as the server auth gate',
      'storage': 'drawn as putLocal in JT Storage',
      'accounts and cloud sync': 'drawn as put and CLOUD_DOWN in JT Storage',
      'Credits': 'the browser half, drawn as hosted in JT Board Search',
      'jobs': 'drawn as addJobs, keyOf and rankOf',
      'company discovery': 'drawn as addSuggested in JT Intake',
      'scoring prompt, built from THIS person': 'drawn as sysPrompt in JT Scoring',
      'auto-scoring': 'drawn as autoScore in JT Intake',
      'cold target': 'drawn as coldDialog in JT Intake',
      'ATS feeds': 'drawn as atsPull in JT Board Search',
      'Apify: board search via Google': 'drawn as portalsFor and buildBoardQueries',
      'board search: every source\'s results, scored, 50+ kept': 'drawn across JT Board Search',
      'the colour law, in code': 'drawn as the cascade in JT Render',
      'Unapplied': 'drawn as renderUnapplied in JT Render',
      'backup, restore, and sharing': 'drawn as importBackup in JT Intake',
    },
  },
};
